import json
import os

import streamlit as st
from dotenv import load_dotenv
from openai import OpenAI
from pypdf import PdfReader

load_dotenv()

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "fireworks").lower()

FIREWORKS_API_KEY = os.getenv("FIREWORKS_API_KEY", "")
FIREWORKS_MODEL = os.getenv("FIREWORKS_MODEL", "accounts/fireworks/models/gemma2-9b-it")
FIREWORKS_BASE_URL = "https://api.fireworks.ai/inference/v1"

HF_TOKEN = os.getenv("HF_TOKEN", "")
HF_MODEL = os.getenv("HF_MODEL", "mistralai/Mistral-7B-Instruct-v0.3")

SYSTEM_PROMPT = """You are ClarityAI, an assistant that reads contracts, terms of service, \
leases, and offer letters and explains them in plain language for people with no legal \
background.

Given a document, respond with ONLY a JSON object (no markdown, no commentary) in this exact \
shape:

{
  "overall_risk_score": <integer 0-100, 0 = totally safe, 100 = extremely risky>,
  "summary": "<2-3 sentence plain-language summary of what this document means for the person signing it>",
  "clauses": [
    {
      "excerpt": "<short quote or paraphrase of the clause>",
      "risk_level": "<low|medium|high>",
      "explanation": "<one sentence, plain language, why this matters to them>",
      "negotiation_tip": "<one sentence: a concrete, specific ask they could make to fix or soften this clause. Empty string if the clause is low risk and not worth pushing back on.>"
    }
  ]
}

Include 3-8 of the most important clauses, prioritizing anything risky, unusual, or costly. \
If the document is genuinely low-risk and standard, say so honestly and keep the clause list short."""

VERDICTS = [
    (20, "Looks Standard", "check_circle", "#2e7d32"),
    (50, "Read Carefully", "warning", "#e6a700"),
    (75, "Negotiate Before Signing", "construction", "#e65100"),
    (101, "Proceed With Caution", "report", "#c62828"),
]


def verdict_for_score(score: int):
    for threshold, label, icon, color in VERDICTS:
        if score < threshold:
            return label, icon, color
    return VERDICTS[-1][1], VERDICTS[-1][2], VERDICTS[-1][3]


def material_icon(name: str, color: str = "inherit", size: int = 20) -> str:
    return (
        f'<span class="material-symbols-outlined" '
        f'style="font-size:{size}px; color:{color}; vertical-align:middle;">{name}</span>'
    )


def build_report_markdown(result: dict) -> str:
    score = result.get("overall_risk_score", 0)
    label, _, _ = verdict_for_score(score)
    lines = [
        "# ClarityAI Risk Report",
        f"**Verdict:** {label}  ",
        f"**Risk score:** {score}/100",
        "",
        "## Summary",
        result.get("summary", ""),
        "",
        "## Flagged clauses",
    ]
    for clause in result.get("clauses", []):
        lines.append(f"- **[{clause.get('risk_level', '').upper()}]** {clause.get('excerpt', '')}")
        lines.append(f"  - Why it matters: {clause.get('explanation', '')}")
        tip = clause.get("negotiation_tip", "")
        if tip:
            lines.append(f"  - What to ask for: {tip}")
    lines.append("")
    lines.append("_Generated by ClarityAI — not legal advice._")
    return "\n".join(lines)


def extract_text(uploaded_file) -> str:
    if uploaded_file.name.lower().endswith(".pdf"):
        reader = PdfReader(uploaded_file)
        return "\n".join(page.extract_text() or "" for page in reader.pages)
    return uploaded_file.read().decode("utf-8", errors="ignore")


def parse_json_response(content: str) -> dict:
    content = content.strip()
    if content.startswith("```"):
        content = content.strip("`")
        content = content.split("\n", 1)[1] if "\n" in content else content
        if content.lower().startswith("json"):
            content = content[4:]
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        from json_repair import repair_json

        return json.loads(repair_json(content))


def analyze_document(text: str) -> dict:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": text[:15000]},
    ]

    if LLM_PROVIDER == "huggingface":
        from huggingface_hub import InferenceClient

        client = InferenceClient(token=HF_TOKEN)
        response = client.chat_completion(messages=messages, model=HF_MODEL, max_tokens=1500, temperature=0.2)
        content = response.choices[0].message.content
    else:
        client = OpenAI(api_key=FIREWORKS_API_KEY, base_url=FIREWORKS_BASE_URL)
        response = client.chat.completions.create(
            model=FIREWORKS_MODEL,
            messages=messages,
            temperature=0.2,
            response_format={"type": "json_object"},
        )
        content = response.choices[0].message.content

    return parse_json_response(content)


def risk_color(level: str) -> str:
    return {"low": "#2e7d32", "medium": "#e6a700", "high": "#c62828"}.get(level.lower(), "#888")


st.set_page_config(page_title="ClarityAI", page_icon=":material/description:", layout="centered")

st.markdown(
    '<link rel="stylesheet" '
    'href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" />',
    unsafe_allow_html=True,
)

st.markdown(
    f'<h1>{material_icon("description", size=34)} ClarityAI</h1>',
    unsafe_allow_html=True,
)
st.caption("Paste a contract, ToS, lease, or offer letter — get a plain-language risk breakdown, powered by Gemma on Fireworks AI.")

if LLM_PROVIDER == "huggingface" and not HF_TOKEN:
    st.warning("HF_TOKEN is not set. Add it to your .env file before analyzing a document.")
elif LLM_PROVIDER != "huggingface" and not FIREWORKS_API_KEY:
    st.warning("FIREWORKS_API_KEY is not set. Add it to your .env file before analyzing a document.")

tab_paste, tab_upload = st.tabs(["Paste text", "Upload file"])

document_text = ""
with tab_paste:
    document_text = st.text_area("Paste the document text here", height=250, placeholder="I hereby agree that...")
with tab_upload:
    uploaded = st.file_uploader("Upload a .txt or .pdf file", type=["txt", "pdf"])
    if uploaded is not None:
        document_text = extract_text(uploaded)
        st.success(f"Loaded {len(document_text)} characters from {uploaded.name}")

analyze_clicked = st.button("Analyze document", type="primary", icon=":material/search:")

if analyze_clicked and not document_text.strip():
    st.warning("Please paste or upload a document first.")
elif analyze_clicked:
    with st.spinner("Reading the fine print..."):
        try:
            result = analyze_document(document_text)
        except Exception as exc:
            st.error(f"Analysis failed: {exc}")
            result = None

    if result:
        score = result.get("overall_risk_score", 0)
        label, verdict_icon, verdict_color = verdict_for_score(score)

        st.markdown(
            f"""<div style="border: 2px solid {verdict_color}; border-radius: 8px; padding: 14px 18px; margin-bottom: 16px; text-align: center;">
            {material_icon(verdict_icon, color=verdict_color, size=28)}
            <span style="font-size: 1.3em; font-weight: 700; color: {verdict_color};"> {label}</span>
            </div>""",
            unsafe_allow_html=True,
        )

        st.subheader("Overall risk")
        st.progress(min(max(score, 0), 100) / 100)
        st.metric("Risk score", f"{score}/100")

        st.subheader("Summary")
        st.write(result.get("summary", "No summary provided."))

        st.subheader("Flagged clauses")
        for clause in result.get("clauses", []):
            level = clause.get("risk_level", "low")
            color = risk_color(level)
            tip = clause.get("negotiation_tip", "")
            tip_html = (
                f'<br/>{material_icon("forum", color=color, size=16)} '
                f'<b>Ask for:</b> {tip}'
                if tip
                else ""
            )
            st.markdown(
                f"""<div style="border-left: 4px solid {color}; padding: 8px 12px; margin-bottom: 10px; background: rgba(128,128,128,0.06);">
                <b style="color:{color}; text-transform:uppercase;">{level}</b><br/>
                <i>{clause.get('excerpt', '')}</i><br/>
                {clause.get('explanation', '')}
                {tip_html}
                </div>""",
                unsafe_allow_html=True,
            )

        st.download_button(
            "Download full Risk Report",
            data=build_report_markdown(result),
            file_name="clarityai_risk_report.md",
            mime="text/markdown",
            icon=":material/download:",
        )
